spring.application.name=EmailService
server.port=8084
server.address=0.0.0.0


eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
management.endpoints.web.exposure.include=*
# -------------------- Database Configuration --------------------
spring.datasource.url=jdbc:mysql://localhost:3306/kafka_project
spring.datasource.username=root
spring.datasource.password=Radha@2322
spring.jpa.hibernate.ddl-auto=update
#======================================================================
spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.group-id=email-group-v2
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

spring.kafka.consumer.properties.spring.json.trusted.packages=*

spring.kafka.consumer.properties.spring.json.type.mapping=com.kafkaproject.orderService.dto.OrderCreatedEvent:emailapi.EmailService.dto.OrderCreatedEvent